=== dseiler/payit/doc/paynet/CUX_V1.0.dtd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Hans JÃ¶rg Beltle (SAP (Schweiz) AG) --><!--DTD generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><!ELEMENT ClientCookie (#PCDATA)><!ELEMENT CommunicationEDI (InvoiceFormat, ID, Password?)><!ELEMENT CommunicationPDF (ID, Password?)><!ELEMENT CustomerPID (#PCDATA)><!ELEMENT DeactivationEDI (InvoiceFormat)><!ELEMENT DeactivationPDF ANY><!ELEMENT EDIActivationMessage (SignOnRq, TrnRq, EDIActivationRequest)><!ELEMENT EDIActivationMessageResponse (SignOnRs, TrnRs, EDIActivationResponse)><!ELEMENT EDIActivationRequest (CustomerPID, (CommunicationEDI?, CommunicationPDF?))><!ELEMENT EDIActivationResponse EMPTY><!ELEMENT EDIDeactivationMessage (SignOnRq, TrnRq, EDIDeactivationRequest)><!ELEMENT EDIDeactivationMessageResponse (SignOnRs, TrnRs, EDIDeactivationResponse)><!ELEMENT EDIDeactivationRequest (CustomerPID, (DeactivationEDI?, DeactivationPDF?))><!ELEMENT EDIDeactivationResponse EMPTY><!ELEMENT ID (#PCDATA)><!ATTLIST ID	IDType (DN | USERNAME) #REQUIRED><!ELEMENT InvoiceFormat (#PCDATA)><!ELEMENT Language (#PCDATA)><!ELEMENT SignOnRq (DtClient, ClientPID, Language)><!ELEMENT SignOnRs (Status, DtClient, DtServer, Language)><!ELEMENT Status (Code, Severity, Message?)><!ELEMENT TrnRq (TrnUID, ClientCookie?)><!ELEMENT TrnRs (TrnUID, ClientCookie?, Status)><!ELEMENT TrnUID (#PCDATA)><!ELEMENT Password (#PCDATA)><!ELEMENT DtClient (#PCDATA)><!ELEMENT ClientPID (#PCDATA)><!ELEMENT DtServer (#PCDATA)><!ELEMENT Code (#PCDATA)><!ELEMENT Severity (#PCDATA)><!ELEMENT Message (#PCDATA)>

=== dseiler/payit/conf/EDIActivation.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE EDIActivationMessage SYSTEM "CUX_V1.0.dtd">
<EDIActivationMessage xmlns="urn:CUXInterfaces:DataTypes">
	<SignOnRq>
		<DtClient>2004-08-10T10:07:24.587Z</DtClient>
		<ClientPID>41010247375633592</ClientPID>
		<Language>GER</Language>
	</SignOnRq>
	<TrnRq>
		<TrnUID>ID0000063</TrnUID>
	</TrnRq>
	<EDIActivationRequest>
		<CustomerPID>41010247375633592</CustomerPID>
		<CommunicationEDI>
			<InvoiceFormat>EIXML_LIGHT</InvoiceFormat>
			<ID IDType="USERNAME">PI_41010247375633592</ID>
			<Password>TestPayIt_11</Password>
		</CommunicationEDI>
		<CommunicationPDF>
			<ID IDType="USERNAME">PI_41010247375633592_MM</ID>
			<Password>TestPayIt_11</Password>
		</CommunicationPDF>
	</EDIActivationRequest>
</EDIActivationMessage>
